site_name: FaBo Donkey Docs
theme:
    name: material
    language: 'ja'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - fontawesome_markdown
  - codehilite:
      linenums: true
  - admonition
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"  